"""Added Message model

Revision ID: 22b7db17c0a1
Revises: 53d260a0444b
Create Date: 2025-03-18 17:50:07.058982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '22b7db17c0a1'
down_revision = '53d260a0444b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
